Viajes/Viajes/Controllers/PaisesController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajes.Data;
using Viajes.Models;
using Viajes.Models.ViewModels;
using Viajes.Services;

namespace Viajes.Controllers
{
    public class PaisesController : Controller
    {
        private readonly IPaises _paisesServices;

        public PaisesController(IPaises paisesServices)
        {
            _paisesServices = paisesServices;
        }

        // GET: Paises
        public async Task<IActionResult> Index()
        {
            AgruparPaisesVM apvm = new AgruparPaisesVM
            {
                Paises = await _paisesServices.GetPaisesAsync(),
                PaisContinente = _paisesServices.GetContinentes()
            };

            return View(apvm);
        }

        // GET: Paises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _paisesServices.GetPaisByIdAsync(id);
            if (pais == null)
            {
                return NotFound();
            }

            return View(pais);
        }

        // GET: paises/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: paises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Pais pais)
        {
            if (ModelState.IsValid)
            {
                await _paisesServices.CreatePaisAsync(pais);
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }

        // GET: paises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _paisesServices.GetPaisByIdAsync(id);
            if (pais == null)
            {
                return NotFound();
            }
            return View(pais);
        }

        // POST: paises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Tipo,Nombre,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Pais pais)
        {
            if (id != pais.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _paisesServices.UpdatePaisAsync(pais);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_paisesServices.PaisExists(pais.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }

        // GET: paises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _paisesServices.GetPaisByIdAsync(id);
            if (pais == null)
            {
                return NotFound();
            }

            return View(pais);
        }

        // POST: paises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pais = await _paisesServices.GetPaisByIdAsync(id);
            await _paisesServices.DeletePaisAsync(pais);
            return RedirectToAction(nameof(Index));
        }

        //private bool PaisExists(int id)
        //{
        //    return _context.Paises.Any(e => e.Id == id);
        //}
    }
}

Viajes/Viajes/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Viajes.Data;
using Viajes.Models;
using Viajes.Models.ViewModels;
using Viajes.Services;

namespace Viajes.Controllers
{
    public class PlanesController : Controller
    {
        private readonly IPlanes _planesServices;
        private readonly ICiudades _ciudadesServices;
        private readonly IPaises _paisesServices;
        private readonly UserManager<AppUser> _userManager;

        public PlanesController(IPlanes planesServices, ICiudades ciudadesServices, IPaises paisesServices, UserManager<AppUser> userManager)
        {
            _planesServices = planesServices;
            _ciudadesServices = ciudadesServices;
            _paisesServices = paisesServices;
            _userManager = userManager;
        }

        // GET: Planes
        public async Task<IActionResult> Index(string ciudad, string tipo)
        {

            ListaPlanPorCiudadVM lppcvm = new ListaPlanPorCiudadVM
            {
                Paises = await _paisesServices.GetPaisesAsync(),
                PaisContinente = _paisesServices.GetContinentes(),
                TiposPlan = _planesServices.GetTipos(),
                Planes = await _planesServices.GetPlanesByCiudadyTipoAsync(ciudad, tipo)
                //Ciudades = await _ciudadesServices.GetCiudadesByPaisIdAsync(paisId)
            };
            return View(lppcvm);
        }

        public async Task<IActionResult> CityPlan(int ciudadId)
        {
            ListaPlanPorCiudadVM lppcvm = new ListaPlanPorCiudadVM
            {
                Ciudad = await _ciudadesServices.GetCiudadByIdAsync(ciudadId),
                Planes = await _planesServices.GetPlanesByCiudadIdAsync(ciudadId)
            };
            return View(lppcvm);
        }

        // GET: Planes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _planesServices.GetPlanByIdAsync(id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }
        
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Actividad()
        {

            ListaPlanPorCiudadVM lppcvm = new ListaPlanPorCiudadVM
            {
                Planes = await _planesServices.GetPlanesAsync(),
                FechasPlan = _planesServices.GetFechas(),
                TiposPlan=_planesServices.GetTipos(),

            };
            return View(lppcvm);
        }
       
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AprobarPlan(int planId)
        {
            Plan plan = await _planesServices.GetPlanByIdAsync(planId);
            plan.Revisado = true;
            await _planesServices.UpdatePlanAsync(plan);
            return Redirect("Actividad");
        }


        [Authorize]
        public async Task<IActionResult> CrearPlan(int ciudadId)
        {
            Ciudad ciudad = await _ciudadesServices.GetCiudadByIdAsync(ciudadId);
            AppUser user = await _userManager.GetUserAsync(User);
            Plan nuevoPlan = new Plan
            {
                Tipo = "",
                Nombre = "",
                Descripcion = "",
                Imagen = "",
                Ciudad = ciudad,
                UsuarioId = user.Id,

                FechaPublicacion = DateTime.Now,
                ValoracionMedia = 0,
                CantidadValoraciones = 0,
            };

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                nuevoPlan.Revisado = true;
            }
            else
            {
                nuevoPlan.Revisado = false;
            }

            return View(nuevoPlan);
        }
        [HttpPost]
        public async Task<IActionResult> ConfirmarPlan([Bind("Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones,CiudadId,UsuarioId")]Plan plan)
        {
            await _planesServices.CreatePlanAsync(plan);

            return RedirectToAction("CityPlan", new { ciudadId = plan.CiudadId });
        }


        // GET: Planes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Planes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                await _planesServices.CreatePlanAsync(plan);
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }

        // GET: Planes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _planesServices.GetPlanByIdAsync(id);
            if (plan == null)
            {
                return NotFound();
            }
            return View(plan);
        }

        // POST: Planes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Plan plan)
        {
            if (id != plan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _planesServices.UpdatePlanAsync(plan);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_planesServices.PlanExists(plan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }

        // GET: Planes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _planesServices.GetPlanByIdAsync(id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plan = await _planesServices.GetPlanByIdAsync(id);
            await _planesServices.DeletePlanAsync(plan);
            return RedirectToAction(nameof(Index));
        }

        //private bool PlanExists(int id)
        //{
        //    return _context.Planes.Any(e => e.Id == id);
        //}
    }
}

Viajes/Viajes/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> _signInManager
@inject UserManager<AppUser> _userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Viajes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/fae805ac08.js" crossorigin="anonymous"></script>
</head>
<body>
    <header id="cabeceraComun">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Paises" asp-action="Index">
                    <div class="row">
                        <img src="https://i.pinimg.com/originals/10/a1/a2/10a1a2f65b58b827756ad4577da0656c.png" id="logotipo" />
                        <div class="logotexto">
                            <p>MONARCH <br />PLANNER</p>
                        </div>
                    </div>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Planes" asp-action="Index">Descubre</a>
                            </li>*@
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <div id="mySidenav" class="sidenav">

                <a asp-area="" asp-controller="Planes" asp-action="Index" id="about">Descubre &nbsp; <i class="fab fa-telegram-plane"></i></a>

                @if (_signInManager.IsSignedIn(User))
                {
            <a asp-area="Identity" asp-page="/Account/Manage/Index" id="blog">Mi perfil &nbsp;&nbsp; <i class="fa fa-user" aria-hidden="true"></i></a>
                    <a href="#" id="projects">Mis guías &nbsp; <i class="fas fa-clipboard-list"></i></a>
                }
                @if (_signInManager.IsSignedIn(User))
                {
                    AppUser user = await _userManager.GetUserAsync(User);
                    @if (await _userManager.IsInRoleAsync(user, "Admin"))
                    {
                        <a asp-area="" asp-controller="Planes" asp-action="Actividad" id="contact">Áctividad &nbsp; <i class="fas fa-chart-line"></i></a>
                    }
                }
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Viajes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>