Viajes/Viajes/Controllers/CiudadesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajes.Data;
using Viajes.Models;
using Viajes.Models.ViewModels;
using Viajes.Services;

namespace Viajes.Controllers
{
    public class CiudadesController : Controller
    {
        private readonly ICiudades _ciudadesServices;
        private readonly IPaises _paisesServices;

        public CiudadesController(ICiudades ciudadesServices, IPaises paisesServices)
        {
            _ciudadesServices = ciudadesServices;
            _paisesServices = paisesServices;
        }

        // GET: Ciudades
        public async Task<IActionResult> Index()
        {       
            return View(await _ciudadesServices.GetCiudadesAsync());
        }

        public async Task<IActionResult> CountryCity(int paisId)
        {
            ListaCiudadPorPaisVM lcppvm = new ListaCiudadPorPaisVM
            {
                Pais = await _paisesServices.GetPaisByIdAsync(paisId),
                Ciudades = await _ciudadesServices.GetCiudadesByPaisIdAsync(paisId)
            };
            return View(lcppvm);
        }


        // GET: Ciudades/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudad = await _ciudadesServices.GetCiudadByIdAsync(id);
            if (ciudad == null)
            {
                return NotFound();
            }

            return View(ciudad);
        }

        // GET: Ciudades/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ciudades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Ciudad ciudad)
        {
            if (ModelState.IsValid)
            {
                await _ciudadesServices.CreateCiudadAsync(ciudad);
                return RedirectToAction(nameof(Index));
            }
            return View(ciudad);
        }

        // GET: Ciudades/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudad = await _ciudadesServices.GetCiudadByIdAsync(id);
            if (ciudad == null)
            {
                return NotFound();
            }
            return View(ciudad);
        }

        // POST: Ciudades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Ciudad ciudad)
        {
            if (id != ciudad.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _ciudadesServices.UpdateCiudadAsync(ciudad);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_ciudadesServices.CiudadExists(ciudad.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ciudad);
        }

        // GET: Ciudades/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ciudad = await _ciudadesServices.GetCiudadByIdAsync(id);
            if (ciudad == null)
            {
                return NotFound();
            }

            return View(ciudad);
        }

        // POST: Ciudades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ciudad = await _ciudadesServices.GetCiudadByIdAsync(id);
            await _ciudadesServices.DeleteCiudadAsync(ciudad);
            return RedirectToAction(nameof(Index));
        }

        //private bool CiudadExists(int id)
        //{
        //    return _context.Ciudades.Any(e => e.Id == id);
        //}
    }
}

Viajes/Viajes/Controllers/PaisesController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajes.Data;
using Viajes.Models;
using Viajes.Models.ViewModels;
using Viajes.Services;

namespace Viajes.Controllers
{
    public class PaisesController : Controller
    {
        private readonly IPaises _paisesServices;

        public PaisesController(IPaises paisesServices)
        {
            _paisesServices = paisesServices;
        }

        // GET: Paises
        public async Task<IActionResult> Index()
        {
            AgruparPaisesVM apvm = new AgruparPaisesVM
            {
                Paises = await _paisesServices.GetPaisesAsync(),
                PaisContinente = _paisesServices.GetContinentes()
            };

            return View(apvm);
        }

        // GET: Paises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _paisesServices.GetPaisByIdAsync(id);
            if (pais == null)
            {
                return NotFound();
            }

            return View(pais);
        }

        // GET: paises/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: paises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Pais pais)
        {
            if (ModelState.IsValid)
            {
                await _paisesServices.CreatePaisAsync(pais);
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }

        // GET: paises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _paisesServices.GetPaisByIdAsync(id);
            if (pais == null)
            {
                return NotFound();
            }
            return View(pais);
        }

        // POST: paises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Tipo,Nombre,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Pais pais)
        {
            if (id != pais.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _paisesServices.UpdatePaisAsync(pais);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_paisesServices.PaisExists(pais.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }

        // GET: paises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pais = await _paisesServices.GetPaisByIdAsync(id);
            if (pais == null)
            {
                return NotFound();
            }

            return View(pais);
        }

        // POST: paises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pais = await _paisesServices.GetPaisByIdAsync(id);
            await _paisesServices.DeletePaisAsync(pais);
            return RedirectToAction(nameof(Index));
        }

        //private bool PaisExists(int id)
        //{
        //    return _context.Paises.Any(e => e.Id == id);
        //}
    }
}

Viajes/Viajes/Views/Paises/Create.cshtml
@model Viajes.Models.Pais

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pais</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continente" class="control-label"></label>
                <input asp-for="Continente" class="form-control" />
                <span asp-validation-for="Continente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Viajes/Viajes/Views/Paises/Delete.cshtml
@model Viajes.Models.Pais

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pais</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Viajes/Viajes/Views/Paises/Details.cshtml
@model Viajes.Models.Pais

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pais</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Imagen)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Continente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Continente)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Viajes/Viajes/Views/Paises/Edit.cshtml
@model Viajes.Models.Pais

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pais</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Continente" class="control-label"></label>
                <input asp-for="Continente" class="form-control" />
                <span asp-validation-for="Continente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Viajes/Viajes/Views/Paises/Index.cshtml
@model Viajes.Models.ViewModels.AgruparPaisesVM
@*@{
        ViewData["Title"] = "Index";
    }*@

<h1 class="text-center encabezado">¿DÓNDE QUIERES IR HOY?</h1>


<div class="align-items-center">
    @foreach (var continente in Model.PaisContinente)
    {
        int cont = 1;
        <h3 class="text-center subencabezado">@continente.ToUpper()</h3>

        <div class="carousel slide carousel-fade paisCar" id="carouselExampleFade-@continente" data-interval="2000" data-ride="carousel">
            <div class="carousel-inner">
                @foreach (var pais in Model.Paises)
                {
                    if (pais.Continente == continente && cont == 1)
                    {
                        <div class="card bg-dark text-white carousel-item active">
                            <img src="@pais.Imagen" class="card-img d-block w-100 imagenPais" alt="@pais.Nombre">
                            <div class="card-img-overlay">
                                <a asp-controller="Ciudades" asp-action="CountryCity" asp-route-paisId="@pais.Id">
                                    <h3 class="card-title tituloPais">@pais.Nombre.ToUpper()</h3>
                                </a>
                            </div>
                        </div>
                        cont++;
                    }

                    else if (pais.Continente == continente && cont > 1)
                    {
                        <div class="card bg-dark text-white carousel-item">
                            <img src="@pais.Imagen" class="card-img d-block w-100 imagenPais" alt="@pais.Nombre">
                            <div class="card-img-overlay">
                                <a asp-controller="Ciudades" asp-action="CountryCity" asp-route-paisId="@pais.Id">
                                    <h3 class="card-title tituloPais">@pais.Nombre.ToUpper()</h3>
                                </a>
                            </div>
                        </div>
                    }
                }
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade-@continente" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade-@continente" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

    }
</div>






@*<h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Continente)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Imagen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Continente)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@