Viajes/Viajes/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Viajes.Data;
using Viajes.Models;
using Viajes.Models.ViewModels;
using Viajes.Services;

namespace Viajes.Controllers
{
    public class PlanesController : Controller
    {
        private readonly IPlanes _planesServices;
        private readonly ICiudades _ciudadesServices;
        private readonly IPaises _paisesServices;
        private readonly UserManager<AppUser> _userManager;

        public PlanesController(IPlanes planesServices, ICiudades ciudadesServices, IPaises paisesServices, UserManager<AppUser> userManager)
        {
            _planesServices = planesServices;
            _ciudadesServices = ciudadesServices;
            _paisesServices = paisesServices;
            _userManager = userManager;
        }

        // GET: Planes
        public async Task<IActionResult> Index(string ciudad, string tipo)
        {

            ListaPlanPorCiudadVM lppcvm = new ListaPlanPorCiudadVM
            {
                Paises = await _paisesServices.GetPaisesAsync(),
                PaisContinente = _paisesServices.GetContinentes(),
                TiposPlan = _planesServices.GetTipos(),
                Planes = await _planesServices.GetPlanesByCiudadyTipoAsync(ciudad, tipo)
                //Ciudades = await _ciudadesServices.GetCiudadesByPaisIdAsync(paisId)
            };
            return View(lppcvm);
        }

        public async Task<IActionResult> CityPlan(int ciudadId)
        {
            ListaPlanPorCiudadVM lppcvm = new ListaPlanPorCiudadVM
            {
                Ciudad = await _ciudadesServices.GetCiudadByIdAsync(ciudadId),
                Planes = await _planesServices.GetPlanesByCiudadIdAsync(ciudadId)
            };
            return View(lppcvm);
        }

        // GET: Planes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _planesServices.GetPlanByIdAsync(id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }
        
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Actividad()
        {

            ListaPlanPorCiudadVM lppcvm = new ListaPlanPorCiudadVM
            {
                Planes = await _planesServices.GetPlanesAsync(),
                FechasPlan = _planesServices.GetFechas(),
                TiposPlan=_planesServices.GetTipos(),

            };
            return View(lppcvm);
        }
       
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AprobarPlan(int planId)
        {
            Plan plan = await _planesServices.GetPlanByIdAsync(planId);
            plan.Revisado = true;
            await _planesServices.UpdatePlanAsync(plan);
            return Redirect("Actividad");
        }


        [Authorize]
        public async Task<IActionResult> CrearPlan(int ciudadId)
        {
            Ciudad ciudad = await _ciudadesServices.GetCiudadByIdAsync(ciudadId);
            AppUser user = await _userManager.GetUserAsync(User);
            Plan nuevoPlan = new Plan
            {
                Tipo = "",
                Nombre = "",
                Descripcion = "",
                Imagen = "",
                Ciudad = ciudad,
                UsuarioId = user.Id,

                FechaPublicacion = DateTime.Now,
                ValoracionMedia = 0,
                CantidadValoraciones = 0,
            };

            if (await _userManager.IsInRoleAsync(user, "Admin"))
            {
                nuevoPlan.Revisado = true;
            }
            else
            {
                nuevoPlan.Revisado = false;
            }

            return View(nuevoPlan);
        }
        [HttpPost]
        public async Task<IActionResult> ConfirmarPlan([Bind("Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones,CiudadId,UsuarioId")]Plan plan)
        {
            await _planesServices.CreatePlanAsync(plan);

            return RedirectToAction("CityPlan", new { ciudadId = plan.CiudadId });
        }


        // GET: Planes/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Planes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Plan plan)
        {
            if (ModelState.IsValid)
            {
                await _planesServices.CreatePlanAsync(plan);
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }

        // GET: Planes/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _planesServices.GetPlanByIdAsync(id);
            if (plan == null)
            {
                return NotFound();
            }
            return View(plan);
        }

        // POST: Planes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tipo,Nombre,Descripcion,Imagen,Revisado,FechaPublicacion,ValoracionMedia,CantidadValoraciones")] Plan plan)
        {
            if (id != plan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _planesServices.UpdatePlanAsync(plan);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_planesServices.PlanExists(plan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(plan);
        }

        // GET: Planes/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _planesServices.GetPlanByIdAsync(id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // POST: Planes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plan = await _planesServices.GetPlanByIdAsync(id);
            await _planesServices.DeletePlanAsync(plan);
            return RedirectToAction(nameof(Index));
        }

        //private bool PlanExists(int id)
        //{
        //    return _context.Planes.Any(e => e.Id == id);
        //}
    }
}

Viajes/Viajes/Controllers/ValoracionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Viajes.Data;
using Viajes.Models;
using Viajes.Models.ViewModels;
using Viajes.Services;

namespace Viajes.Controllers
{
    public class ValoracionesController : Controller
    {
        private readonly IValoraciones _valoracionesServices;
        private readonly IPlanes _planesServices;
        private readonly UserManager<AppUser> _userManager;

        public ValoracionesController(IValoraciones valoracionesServices, IPlanes planesServices, UserManager<AppUser> userManager)
        {
            _valoracionesServices = valoracionesServices;
            _planesServices = planesServices;
            _userManager = userManager;
        }

        // GET: Valoraciones
        public async Task<IActionResult> Index()
        {
            return View(await _valoracionesServices.GetValoracionesAsync());
        }
        [HttpPost]
        public async Task<IActionResult> Valorar(ListaPlanPorCiudadVM listaPlanPorCiudadVM)
        {
            AppUser user = await _userManager.GetUserAsync(User);
            listaPlanPorCiudadVM.Valoracion.Fecha = DateTime.Now;
            listaPlanPorCiudadVM.Valoracion.Usuario = user;

            await _valoracionesServices.CreateValoracionAsync(listaPlanPorCiudadVM.Valoracion);


            Plan plan = await _planesServices.GetPlanByIdAsync(listaPlanPorCiudadVM.Valoracion.PlanId);
            int cantValoraciones = plan.CantidadValoraciones + 1;
            plan.CantidadValoraciones = cantValoraciones;
            if (plan.CantidadValoraciones == 1)
            {
                double mediaValoracion = (plan.ValoracionMedia + listaPlanPorCiudadVM.Valoracion.Puntuacion) / 1;
                plan.ValoracionMedia = mediaValoracion;
            }
            else if (plan.CantidadValoraciones > 1)
            {
                double mediaValoracion = (plan.ValoracionMedia + listaPlanPorCiudadVM.Valoracion.Puntuacion) / 2;
                plan.ValoracionMedia = mediaValoracion;
            }


            await _planesServices.UpdatePlanAsync(plan);

            return RedirectToActionPermanent("CityPlan", "Planes", new { ciudadId = listaPlanPorCiudadVM.Valoracion.Plan.CiudadId });
            //return RedirectToAction("CityPlan", new { ciudadId = plan.CiudadId });

        }

        //public async Task<IActionResult> ComprobarValoracion(ListaPlanPorCiudadVM listaPlanPorCiudadVM)
        //{

        //    return false;
        //}

        // GET: Valoraciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var valoracion = await _valoracionesServices.GetValoracionByIdAsync(id);
            if (valoracion == null)
            {
                return NotFound();
            }

            return View(valoracion);
        }

        // GET: Valoraciones/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Valoraciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fecha,Puntuacion")] Valoracion valoracion)
        {
            if (ModelState.IsValid)
            {
                await _valoracionesServices.CreateValoracionAsync(valoracion);
                return RedirectToAction(nameof(Index));
            }
            return View(valoracion);
        }

        // GET: Valoraciones/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var valoracion = await _valoracionesServices.GetValoracionByIdAsync(id);
            if (valoracion == null)
            {
                return NotFound();
            }
            return View(valoracion);
        }

        // POST: Valoraciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Puntuacion")] Valoracion valoracion)
        {
            if (id != valoracion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _valoracionesServices.UpdateValoracionAsync(valoracion);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_valoracionesServices.ValoracionExists(valoracion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(valoracion);
        }

        // GET: Valoraciones/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var valoracion = await _valoracionesServices.GetValoracionByIdAsync(id);
            if (valoracion == null)
            {
                return NotFound();
            }

            return View(valoracion);
        }

        // POST: Valoraciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var valoracion = await _valoracionesServices.GetValoracionByIdAsync(id);
            await _valoracionesServices.DeleteValoracionAsync(valoracion);
            return RedirectToAction(nameof(Index));
        }

    }
}

Viajes/Viajes/Views/Planes/CityPlan.cshtml
@using Microsoft.AspNetCore.Identity
@model Viajes.Models.ViewModels.ListaPlanPorCiudadVM
@inject UserManager<AppUser> _userManager


<div class="card bg-transparent border-0 text-white m-3" style="width:100%;">
    <img src="@Model.Ciudad.Imagen" class="card-img" style="height:400px;width:auto; object-fit: none;" alt="@Model.Ciudad.Nombre">
    <div class="card-img-overlay text-center">
        <h1 class="card-title paisCiudades">@Model.Ciudad.Nombre.ToUpper()</h1>
        <ul class="row justify-content-center actividadesCiudades">
            <li>Naturaleza </li>
            <li> Cultura </li>
            <li> Ocio </li>
        </ul>
    </div>
</div>

<div class="text-center">
    <a asp-controller="Planes" asp-action="CrearPlan" asp-route-ciudadId="@Model.Ciudad.Id">Crear Plan</a>
</div>

<div class="d-flex align-items-end flex-column w-85">

    @foreach (Plan plan in Model.Planes)
    {
        if (plan.Revisado == true)
        {
            <div class="media planes">
                <img src="@plan.Imagen" class="mr-3 planImagen" alt="@plan.Nombre">
                <div class="media-body">
                    <h5 class="mt-0">@plan.Nombre</h5>
                    @plan.Descripcion
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Tipo: @plan.Tipo</li>
                        <li class="list-group-item">@plan.CantidadValoraciones valoraciones: @plan.ValoracionMedia valoracion media</li>
                    </ul>
                    <div class="card-body">
                        <a class="card-link" data-toggle="collapse" href="#collapseExample-@plan.Id" role="button" aria-expanded="false" aria-controls="collapseExample">
                            Valora este plan
                        </a>
                        <a class="card-link" asp-action="Edit" asp-route-id="@plan.Id">Editar plan</a>
                        <a class="card-link" asp-action="Delete" asp-route-id="@plan.Id">Eliminar plan</a>
                    </div>
                    <div class="collapse" id="collapseExample-@plan.Id">
                        <div class="card card-body">

                            @*@if (Model.Valoracion.UsuarioId == _userManager.GetUserId(User) && plan.Id==Model.Valoracion.PlanId)
                            {

                            }*@

                            <form asp-controller="Valoraciones" asp-action="Valorar">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" id="inlineRadio1" asp-for="@Model.Valoracion.Puntuacion" value=1>
                                    <label class="form-check-label" for="inlineRadio1">1</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" id="inlineRadio2" asp-for="@Model.Valoracion.Puntuacion" value=2>
                                    <label class="form-check-label" for="inlineRadio2">2</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" id="inlineRadio3" asp-for="@Model.Valoracion.Puntuacion" value=3>
                                    <label class="form-check-label" for="inlineRadio3">3</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" id="inlineRadio4" asp-for="@Model.Valoracion.Puntuacion" value=4>
                                    <label class="form-check-label" for="inlineRadio4">4</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" id="inlineRadio5" asp-for="@Model.Valoracion.Puntuacion" value=5>
                                    <label class="form-check-label" for="inlineRadio5">5</label>
                                </div>
                                <input type="hidden" asp-for="@Model.Valoracion.PlanId" value="@plan.Id" />
                                <input type="submit" value="¡Hecho!" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>














@*<p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Revisado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaPublicacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ValoracionMedia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadValoraciones)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Imagen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Revisado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaPublicacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValoracionMedia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadValoraciones)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@

Viajes/Viajes/Views/Planes/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model Viajes.Models.ViewModels.ListaPlanPorCiudadVM
@inject UserManager<AppUser> _userManager
<script src="https://kit.fontawesome.com/fae805ac08.js" crossorigin="anonymous"></script>


<h1 class="text-center encabezado">DESCUBRE PLANES POR TODO EL MUNDO</h1>

<div class="filtros text-center">

    <form asp-action="Index">
        <input type="text" class="botonDescubre" placeholder="Ciudad..." name="ciudad" />
        @*<input type="submit" class="botonDescubre" value="Buscar" />*@
        <select class="botonDescubre" name="tipo" id="selectTipo">
            <option value="">Todos</option>
            @{
                foreach (var tipo in Model.TiposPlan)
                {
                    <option value="@tipo">@tipo</option>
                };
            }
        </select>
        <button type="submit" class="botonDescubre" value=""><i class="fas fa-filter fa-x2"></i></button>
    </form>
</div>

@if (Model.Planes.Count == 0)
{
    <h3>Ningún resultado</h3>
}
else
{
    <div class="d-flex align-items-end flex-column w-85">

        @foreach (Plan plan in Model.Planes)
        {
            if (plan.Revisado == true)
            {

                <div class="media planes">
                    <img src="@plan.Imagen" class="mr-3 planImagen" alt="@plan.Nombre">
                    <div class="media-body">
                        <h5 class="mt-0">@plan.Nombre</h5>
                        @plan.Descripcion
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">@plan.Ciudad.Nombre, @plan.Ciudad.Pais.Nombre</li>
                            <li class="list-group-item">Tipo: @plan.Tipo</li>
                            <li class="list-group-item">@plan.CantidadValoraciones valoraciones: @plan.ValoracionMedia valoración media</li>
                        </ul>
                        <div class="card-body">
                            <a class="card-link" data-toggle="collapse" href="#collapseExample-@plan.Id" role="button" aria-expanded="false" aria-controls="collapseExample">
                                Valora este plan
                            </a>
                            <a class="card-link" asp-action="Edit" asp-route-id="@plan.Id">Editar plan</a>
                            <a class="card-link" asp-action="Delete" asp-route-id="@plan.Id">Eliminar plan</a>
                        </div>
                        <div class="collapse" id="collapseExample-@plan.Id">
                            <div class="card card-body">

                                @*@if (Model.Valoracion.UsuarioId == _userManager.GetUserId(User) && plan.Id==Model.Valoracion.PlanId)
                                    {

                                    }*@

                                <form asp-controller="Valoraciones" asp-action="Valorar">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="inlineRadio1" asp-for="@Model.Valoracion.Puntuacion" value=1>
                                        <label class="form-check-label" for="inlineRadio1">1</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="inlineRadio2" asp-for="@Model.Valoracion.Puntuacion" value=2>
                                        <label class="form-check-label" for="inlineRadio2">2</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="inlineRadio3" asp-for="@Model.Valoracion.Puntuacion" value=3>
                                        <label class="form-check-label" for="inlineRadio3">3</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="inlineRadio4" asp-for="@Model.Valoracion.Puntuacion" value=4>
                                        <label class="form-check-label" for="inlineRadio4">4</label>
                                    </div>
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="radio" id="inlineRadio5" asp-for="@Model.Valoracion.Puntuacion" value=5>
                                        <label class="form-check-label" for="inlineRadio5">5</label>
                                    </div>
                                    <input type="hidden" asp-for="@Model.Valoracion.PlanId" value="@plan.Id" />
                                    <input type="submit" value="¡Hecho!" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
};


















@*<div class="filtros text-center">
        <h4 class="text-center subencabezado">Filtra por país</h4>
        <form asp-action="Index">
            @foreach (var continente in Model.PaisContinente)
            {
                <h3 class="subencabezado">@continente</h3>

                @foreach (var pais in Model.Paises)
                {
                    <div asp-action="" class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="inlineCheckbox-@pais.Id" name="paisSelect" value="@pais.Id">
                        <label class="form-check-label" for="inlineCheckbox-@pais.Id">@pais.Nombre</label>
                    </div>
                }

            }
            <input type="submit" value="Filtrar" />
        </form>
            <h4 class="text-center subencabezado">Filtra por tipo</h4>
            @foreach (var plan in Model.Planes)
            {
                int cont = 1;
                    <h3 class="subencabezado">@continente</h3>

                    @foreach (var pais in Model.Paises)
                    {
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="inlineCheckbox-@cont" value="@pais.Id">
                            <label class="form-check-label" for="inlineCheckbox-@cont">1</label>
                        </div>
                        cont++;
                    }

            }

    </div>*@






@*<p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Tipo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Revisado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaPublicacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ValoracionMedia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadValoraciones)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                   <img src="@Html.DisplayFor(modelItem => item.Imagen)" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Revisado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaPublicacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ValoracionMedia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadValoraciones)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
    }
        </tbody>
    </table>*@